<a href="https://colab.research.google.com/github/CharlieHubbard7/NFLResearch/blob/main/(6_2_26)_NFL_Research.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NFL Research

This notebook contains my work for the third week of work with Professor Ron Yurko at Carnegie Mellon's Sports Analytics Center. I use Madden ratings to explore what stats teams value in players of different position groups

##Data Wrangling

### Installs and Imports

In [2]:
!pip install nflreadpy #This is from the NFLverse package: https://github.com/nflverse/nflreadpy
!pip install rapidfuzz -q #This helps match the NFL roster with the madden data

Collecting nflreadpy
  Downloading nflreadpy-0.1.5-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.32.4)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (1.35.2)
Requirement already satisfied: platformdirs>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.9.6)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.67.3)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.14.1)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->nflreadpy) (1.35.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2026.5.20)
Downloading nflreadpy-0.1.5-py3-none-any.whl (30 kB)
Installing collected packages: nflreadpy
Successfully installed nflreadpy-0.1.5
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 36.4 MB/s eta 0:00:00

In [3]:
import pandas as pd
import numpy as np
import string
import re
import math
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns
import nflreadpy as nfl
from rapidfuzz import fuzz, process
pd.set_option('display.max_columns', 250)
pd.set_option('display.min_rows', 10)

### NFL Verse Stats

In [13]:
pbp = nfl.load_pbp().to_pandas() # play-by-play data
player_stats = nfl.load_player_stats().to_pandas() # player game or season statistics
team_stats = nfl.load_team_stats().to_pandas() # team game or season statistics
# schedules = nfl.load_schedules().to_pandas() # game schedules and results
players = nfl.load_players().to_pandas() # player information
rosters = nfl.load_rosters().to_pandas() # team rosters
rosters_weekly = nfl.load_rosters_weekly().to_pandas() # team rosters by season-week
snap_counts = nfl.load_snap_counts().to_pandas() # snap counts
nextgen_stats = nfl.load_nextgen_stats().to_pandas() # advanced stats from nextgenstats.nfl.com
ftn_charting = nfl.load_ftn_charting().to_pandas() # charted stats from ftnfantasy.com/data
participation = nfl.load_participation().to_pandas() # participation data (historical)
draft_picks = nfl.load_draft_picks().to_pandas() # nfl draft picks
injuries = nfl.load_injuries().to_pandas() # injury statuses and practice participation
contracts = nfl.load_contracts().to_pandas() # historical contract data from OTC
officials = nfl.load_officials().to_pandas() # officials for each game
combine = nfl.load_combine().to_pandas() # nfl combine results
depth_charts = nfl.load_depth_charts().to_pandas() # depth charts
trades = nfl.load_trades().to_pandas() # trades
ff_playerids = nfl.load_ff_playerids().to_pandas() # ffverse/dynastyprocess player ids
ff_rankings = nfl.load_ff_rankings().to_pandas() # fantasypros rankings
ff_opportunity = nfl.load_ff_opportunity().to_pandas() # expected yards, touchdowns, and fantasy points

### Historical Madden Data

Credit to: https://github.com/theedgepredictor/nfl-madden-data/tree/main/data/madden/dataset for the data collection

In [4]:
madden_long = pd.read_parquet("/content/drive/MyDrive/ipynb stuff/madden_hist.parquet")
madden_long.head()

,player_id,madden_id,pfr_id,fullname,high_pos_group,position_group,position,season,team,last_season_av,overallrating,agility,acceleration,speed,stamina,strength,toughness,injury,awareness,jumping,trucking,archetype,runningstyle,changeofdirection,playrecognition,throwpower,throwaccuracyshort,throwaccuracymid,throwaccuracydeep,playaction,throwonrun,carrying,ballcarriervision,stiffarm,spinmove,jukemove,catching,shortrouterunning,midrouterunning,deeprouterunning,spectacularcatch,catchintraffic,release,runblocking,passblocking,impactblocking,mancoverage,zonecoverage,tackle,hitpower,press,pursuit,kickaccuracy,kickpower,return,year
0,00-0004543,SHANEDRONETT_d_line,DronSh20,Shane Dronett,def,d_line,DL,2001,ATL,1.0,75.0,53.0,65.0,58.0,79.0,84.0,84.0,79.0,81.0,43.0,7.347195,4,11,35.306958,66.518996,11.0,20.0,20.0,20.0,16.696763,19.318944,28.0,-2.261149,-1.546120,2.340851,3.478826,22.0,6.519022,10.549796,11.996476,9.005981,8.412261,8.034401,16.0,16.0,0.483380,15.249485,17.082539,81.0,51.752871,8.673651,66.456748,21.0,24.0,0.675884,2001
1,00-0012842,JASONPETER_d_line,PeteJa20,Jason Peter,def,d_line,DL,2001,CAR,1.0,74.0,66.0,74.0,64.0,84.0,78.0,84.0,80.0,67.0,51.0,7.889415,5,7,47.836493,58.864012,10.0,21.0,21.0,21.0,18.295792,21.480056,24.0,0.980120,-0.375920,8.238861,7.495244,21.0,5.982346,9.869347,12.073328,5.724684,4.637821,9.797546,27.0,18.0,9.782409,19.028072,23.221269,72.0,54.472249,12.652961,69.286862,18.0,19.0,3.772098,2001
2,00-0009978,LEONARDLITTLE_d_line,LittLe00,Leonard Little,def,d_line,DL,2001,LAR,1.0,73.0,72.0,62.0,75.0,65.0,70.0,70.0,82.0,64.0,52.0,25.090824,8,9,51.656422,55.302556,32.0,14.0,14.0,14.0,11.934877,13.800475,24.0,19.994085,18.021897,24.959818,21.045019,40.0,8.751804,11.499611,12.645619,17.544412,14.431167,17.109987,16.0,24.0,-5.096101,32.979157,37.209780,74.0,51.286358,28.416331,72.007990,11.0,33.0,1.131921,2001
3,00-0002142,JUNIORBRYANT_d_line,BryaJu20,Junior Bryant,def,d_line,DL,2001,SF,1.0,72.0,49.0,62.0,55.0,81.0,81.0,84.0,84.0,79.0,43.0,5.111116,5,9,36.576845,65.727568,24.0,11.0,11.0,11.0,9.494538,11.093699,14.0,-8.819708,-2.912042,-5.407254,-5.493794,14.0,7.008726,10.117281,12.240143,-1.108932,-1.319240,1.354661,29.0,27.0,7.181824,14.503342,17.728221,82.0,51.302609,6.509206,64.948565,12.0,14.0,1.162361,2001
4,00-0018054,REINARDWILSON_d_line,WilsRe20,Reinard Wilson,def,d_line,DL,2001,CIN,1.0,69.0,70.0,70.0,65.0,78.0,69.0,78.0,77.0,65.0,50.0,16.121217,7,9,50.852213,56.274011,31.0,16.0,16.0,16.0,16.041897,17.385281,26.0,12.748664,9.218156,18.243457,14.183115,26.0,7.190139,10.575620,11.980324,12.149089,9.289694,10.978948,13.0,9.0,-2.869764,26.808503,31.008670,69.0,51.400124,22.833778,69.883798,17.0,21.0,2.545349,2001

In [8]:

madden_long["rookie_year"] = madden_long.groupby("player_id")["year"].transform("min")
madden_long["years_in_nfl"] = madden_long["year"] - madden_long["rookie_year"] + 1
baseline = (madden_long[madden_long["years_in_nfl"] == 1]
            .set_index("player_id")["overallrating"])
madden_long["baseline_overall"] = madden_long["player_id"].map(baseline)
madden_long["overall_vs_baseline"] = madden_long["overallrating"] - madden_long["baseline_overall"]

## Analysis

### Exploring Variation of Players Rankings

In [18]:
temp = madden_long.query("rookie_year == 2020").sort_values("baseline_overall", ascending = False)
temp

,player_id,madden_id,pfr_id,fullname,high_pos_group,position_group,position,season,team,last_season_av,overallrating,agility,acceleration,speed,stamina,strength,toughness,injury,awareness,jumping,trucking,archetype,runningstyle,changeofdirection,playrecognition,throwpower,throwaccuracyshort,throwaccuracymid,throwaccuracydeep,playaction,throwonrun,carrying,ballcarriervision,stiffarm,spinmove,jukemove,catching,shortrouterunning,midrouterunning,deeprouterunning,spectacularcatch,catchintraffic,release,runblocking,passblocking,impactblocking,mancoverage,zonecoverage,tackle,hitpower,press,pursuit,kickaccuracy,kickpower,return,year,rookie_year,years_in_nfl,baseline_overall,overall_vs_baseline
50362,00-0036321,CHASEYOUNG_19990101,YounCh04,Chase Young,def,d_line,DL,2022,WAS,4.000000,86.000000,86.000000,91.000000,87.000000,80.000000,86.000000,89.000000,88.000000,86.000000,84.000000,34.000000,4,10,70.000000,83.000000,32.000000,28.000000,25.000000,20.000000,15.000000,33.000000,43.000000,36.000000,39.000000,36.000000,38.000000,33.000000,14.000000,6.611093,5.000000,24.000000,25.000000,17.000000,45.000000,45.000000,85.000000,34.000000,47.000000,89.000000,84.000000,27.000000,87.000000,22.000000,14.000000,10.000000,2022,2020.0,3.0,80.0,6.000000
53079,00-0036321,CHASEYOUNG_19990101,YounCh04,Chase Young,def,d_line,DL,2023,WAS,1.000000,85.000000,86.000000,91.000000,87.000000,80.000000,86.000000,89.000000,85.000000,84.000000,84.000000,34.000000,4,10,70.000000,81.000000,32.000000,28.000000,25.000000,20.000000,15.000000,33.000000,43.000000,36.000000,39.000000,36.000000,38.000000,33.000000,14.000000,8.799965,5.000000,24.000000,25.000000,17.000000,45.000000,45.000000,85.000000,34.000000,47.000000,89.000000,84.000000,27.000000,87.000000,22.000000,14.000000,10.000000,2023,2020.0,4.0,80.0,5.000000
44498,00-0036321,CHASEYOUNG_19990101,YounCh04,Chase Young,def,d_line,DL,2020,WAS,11.000000,80.000000,86.000000,91.000000,85.000000,80.000000,86.000000,89.000000,89.000000,74.000000,83.000000,34.000000,4,6,70.000000,71.000000,32.000000,28.000000,25.000000,20.000000,15.000000,33.000000,43.000000,36.000000,39.000000,36.000000,38.000000,33.000000,14.000000,9.943039,5.000000,24.000000,25.000000,17.000000,45.000000,45.000000,85.000000,34.000000,48.000000,83.000000,84.000000,27.000000,84.000000,22.000000,14.000000,10.000000,2020,2020.0,1.0,80.0,0.000000
56047,00-0036321,CHASEYOUNG_19990101,YounCh04,Chase Young,def,d_line,DL,2024,NO,2.000000,85.000000,86.000000,90.000000,86.000000,79.000000,86.000000,89.000000,83.000000,85.000000,84.000000,34.000000,4,10,71.000000,82.000000,32.000000,28.000000,25.000000,20.000000,15.000000,33.000000,43.000000,36.000000,39.000000,36.000000,38.000000,33.000000,14.000000,6.554689,5.000000,24.000000,25.000000,17.000000,45.000000,45.000000,85.000000,34.000000,47.000000,85.000000,84.000000,27.000000,86.000000,22.000000,14.000000,10.000000,2024,2020.0,5.0,80.0,5.000000
47530,00-0036321,CHASEYOUNG_19990101,YounCh04,Chase Young,def,d_line,DL,2021,WAS,14.000000,86.000000,86.000000,91.000000,85.000000,80.000000,86.000000,89.000000,89.000000,86.000000,84.000000,34.000000,4,10,70.000000,83.000000,32.000000,28.000000,25.000000,20.000000,15.000000,33.000000,43.000000,36.000000,39.000000,36.000000,38.000000,33.000000,14.000000,10.000000,5.000000,24.000000,25.000000,17.000000,45.000000,45.000000,85.000000,34.000000,48.000000,89.000000,84.000000,27.000000,87.000000,22.000000,14.000000,10.000000,2021,2020.0,2.0,80.0,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57687,00-0036120,ALEXTAYLOR_19970429,None,Armani Taylor-Prioleau,off,o_line,OL,2024,WAS,3.377049,60.466970,57.518819,68.593378,64.676871,80.657116,83.814191,81.738797,85.739980,64.850515,73.737413,29.060833,2,8,47.868787,22.149143,22.670554,9.144375,8.731648,8.499849,8.050666,8.003914,33.912983,18.665013,23.127280,15.146860,17.530318,32.575075,17.945667,10.871852,8.419528,21.693591,21.980603,19.311084,65.851080,65.486464,79.472316,11.270837,13.039649,35.151445,36.162631,9.978493,28.504360,15.263448,17.369825,10.241859,2024,2020.0,5.0,51.0,9.466970
54662,00-0036120,ALEXTAYLOR_19970429,None,Alex Taylor,off,o_line,OL,2023,DAL,3.585213,61.346491,58.144617,70.523028,64.779694,81.109763,83.700426,81.847233,86.515198,64.084803,74.019275,30.016789,1,5,50.774961,22.013130,23.085786,9.153204,8.707726,8.532124,8.076534,8.096861,34.294607,19.082753,23.608986,15.556030,18.248646,33.021489,17.624484,11.416749,8.848615,21.360015,21.856385,19.301942,66.977691,66.786060,79.023892,11.320195,13.364145,35.845065,36.316294,10.031952,29.237327,15.080296,17.444935,10.170525,2023,2020.0,4.0,51.0,10.346491
48768,00-0036120,ALEXTAYLOR_19970429,None,Alex Taylor,off,o_line,OL,2021,CLE,3.587719,59.979379,58.534473,71.231209,63.181247,80.591965,83.012037,82.707998,85.503323,59.350715,73.332635,29.109786,2,6,51.604300,21.587347,23.116418,9.606818,9.009499,8.576334,8.092829,8.325550,33.062696,18.980921,24.276753,15.345799,17.831438,30.673987,16.964008,12.093978,9.589191,20.327259,20.520589,19.055821,67.195450,66.221828,77.480258,11.823686,13.726163,35.074606,36.695482,9.985386,27.948679,15.300868,18.594666,10.217676,2021,2020.0,2.0,51.0,8.979379
51729,00-0036120,ALEXTAYLOR_19970429,None,Alex Taylor,off,o_line,OL,2022,DAL,3.320843,63.229691,58.914361,70.204491,64.144669,78.781662,83.791329,79.830349,88.018393,63.579763,68.635008,26.345806,2,8,50.521241,20.931965,24.042526,9.822691,9.113069,8.967638,7.798020,8.635333,32.942127,18.262878,21.707546,14.200216,15.415795,28.758033,16.319951,9.449568,8.295810,20.211667,20.479627,18.683552,70.204990,69.366113,77.734596,11.699557,13.509077,32.425143,32.860722,10.170623,29.642335,16.608109,18.458468,9.905270,2022,2020.0,3.0,51.0,12.229691
45768,00-0035909,RYANROBERTS_19961003,None,Ryan Roberts,off,o_line,OL,2020,LAC,3.793282,50.000000,55.000000,73.000000,64.000000,86.000000,79.000000,88.000000,90.000000,49.000000,66.000000,30.000000,2,9,50.000000,15.000000,21.000000,6.000000,6.000000,6.000000,6.000000,6.000000,30.000000,21.000000,29.000000,10.000000,16.000000,36.000000,18.000000,16.051692,15.000000,28.000000,31.000000,22.000000,60.000000,61.000000,78.000000,12.000000,15.000000,22.000000,24.000000,10.000000,18.000000,12.000000,18.000000,10.000000,2020,2020.0,1.0,50.0,0.000000